/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forularios;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Eterna
 */
public final class frmBoltaP extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form frmBoltaP
     */
    DecimalFormat df = new DecimalFormat("#.00");
    public frmBoltaP() {
        initComponents();
        this.boletap();

    }
     frmPerfilEmp empli = new frmPerfilEmp();
     frmCalculoRenta renta = new frmCalculoRenta();

    public void boletap(){
        frmHorasExtras horas = new frmHorasExtras();
        
        //String nombre=frmPerfilEmp.nombre;
        
        T_nombre.setText(frmPerfilEmp.nombre); //NOMBRE
        T_Sueldo_Mes.setText("$"+frmPerfilEmp.sueldo); //SUELDO
        T_Dias_Trabajados.setText(frmPerfilEmp.tiempo); //DIAS TRAABAJADOS
        
                                                                          //OBTENER CANTIDAD DE HRS EXTRA
//        tot_horas_extras.setText(String.valueOf("$"+horas.resuF+""));//TOTAL DE HORAS EXTRAS
//        T_Total_Ingresos1.setText((frmPerfilEmp.sueldo+horas.resuF)                          );
        T_Seguro_ISS.setText(String.valueOf(frmsGravado.vIss));
        T_AFP.setText(String.valueOf((df.format(frmsGravado.vAfp))));
        T_Tot_Descuentos.setText(String.valueOf((df.format(frmsGravado.vAfp +frmsGravado.vIss+renta.isr))        ));
        T_ISR.setText(String.valueOf((df.format(renta.isr))));
        T_Liquido_a_pagar.setText(String.valueOf( (df.format(renta.temp))  ));
        
        
        
    }
     
    //A PARTIR DE AQUI CREAR PDFS
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_Hrs_Extra_Noche = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tot_horas_extras = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        T_Tot_Descuentos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        T_Dias_Trabajados = new javax.swing.JTextField();
        T_Sueldo_Mes = new javax.swing.JTextField();
        T_Seguro_ISS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        T_ISR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        T_AFP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        T_Liquido_a_pagar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        T_Hrs_Extra_Dia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_Generar_PDF = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        T_Total_Ingresos1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_Hrs_Extra_Noche.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Hrs_Extra_Noche, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Liquido a pagar:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        tot_horas_extras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(tot_horas_extras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 230, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Total Descuentos:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        T_Tot_Descuentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Tot_Descuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 140, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Total de Ingreso: ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        T_Dias_Trabajados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Dias_Trabajados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 230, 30));

        T_Sueldo_Mes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Sueldo_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, 30));

        T_Seguro_ISS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Seguro_ISS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 80, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("ISR:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("AFP:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Seguro Social ISS:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        T_ISR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_ISR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 140, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Horas Extras:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        T_AFP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_AFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 140, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Horas Extra Diurna:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        T_Liquido_a_pagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        T_Liquido_a_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_Liquido_a_pagarActionPerformed(evt);
            }
        });
        add(T_Liquido_a_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 230, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Días Trabajados:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        T_Hrs_Extra_Dia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        T_Hrs_Extra_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_Hrs_Extra_DiaActionPerformed(evt);
            }
        });
        add(T_Hrs_Extra_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 230, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Sueldo Mensual:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Descuento");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Descripción Descuento");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Pago");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Boleta: Mensual");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, 20));

        T_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        T_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_nombreActionPerformed(evt);
            }
        });
        add(T_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 380, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Boleta de Pago (Vista previa)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        btn_Generar_PDF.setBackground(new java.awt.Color(255, 51, 51));
        btn_Generar_PDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Generar_PDF.setForeground(new java.awt.Color(255, 204, 204));
        btn_Generar_PDF.setText("Generar PDF");
        btn_Generar_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Generar_PDFActionPerformed(evt);
            }
        });
        add(btn_Generar_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 170, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Hora Extra Nocturna:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        T_Total_Ingresos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(T_Total_Ingresos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 230, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Descripción");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void T_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_nombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_T_nombreActionPerformed

    private void T_Liquido_a_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_Liquido_a_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_Liquido_a_pagarActionPerformed

    private void btn_Generar_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Generar_PDFActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport jp = (JasperReport)
                    JRLoader.loadObject(frmBoltaP.class.getResource("/reportes/boleta_pago.jasper"));
            Map parametros = new HashMap<String,Object>();
            
            parametros.put("nombre", this.T_nombre.getText());
            parametros.put("sueldo_mes", this.T_Sueldo_Mes.getText());
            parametros.put("dias_trabajados", this.T_Dias_Trabajados.getText());
            
            parametros.put("hr_extra", this.T_Hrs_Extra_Dia.getText());
            parametros.put("hr_extra_noche", this.T_Hrs_Extra_Noche.getText());
            parametros.put("tot_hr_extra", this.tot_horas_extras.getText());
            
           parametros.put("tot_ingreso", this.T_Total_Ingresos1.getText());
            parametros.put("liquido_pagar", this.T_Liquido_a_pagar.getText());
            
            parametros.put("iss", this.T_Seguro_ISS.getText());
            parametros.put("afp", this.T_AFP.getText());
            parametros.put("isr", this.T_ISR.getText());
            parametros.put("tot_descuento", this.T_Tot_Descuentos.getText());
            
            JasperPrint imprimir =
                    JasperFillManager.fillReport(jp,parametros ,new JREmptyDataSource());
            JasperViewer verpdf = new JasperViewer(imprimir);
            verpdf.show();
        } catch (JRException e) {
        }
        
    }//GEN-LAST:event_btn_Generar_PDFActionPerformed

    private void T_Hrs_Extra_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_Hrs_Extra_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_Hrs_Extra_DiaActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T_AFP;
    private javax.swing.JTextField T_Dias_Trabajados;
    private javax.swing.JTextField T_Hrs_Extra_Dia;
    private javax.swing.JTextField T_Hrs_Extra_Noche;
    private javax.swing.JTextField T_ISR;
    private javax.swing.JTextField T_Liquido_a_pagar;
    private javax.swing.JTextField T_Seguro_ISS;
    private javax.swing.JTextField T_Sueldo_Mes;
    private javax.swing.JTextField T_Tot_Descuentos;
    private javax.swing.JTextField T_Total_Ingresos1;
    public static javax.swing.JTextField T_nombre;
    private javax.swing.JButton btn_Generar_PDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tot_horas_extras;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
          if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2d);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }


}
