/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forularios;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Eterna
 */
public class frmEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form frmEmpresa
     */
    public frmEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pEmpleado = new javax.swing.JButton();
        Contenedor = new javax.swing.JPanel();

        bg_panel.setBackground(new java.awt.Color(0, 150, 136));
        bg_panel.setPreferredSize(new java.awt.Dimension(1250, 700));

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));

        pEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        pEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        pEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        pEmpleado.setText("Perfil de empleado");
        pEmpleado.setToolTipText("Check what's new!");
        pEmpleado.setBorderPainted(false);
        pEmpleado.setContentAreaFilled(false);
        pEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pEmpleado.setOpaque(true);
        pEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseReleased(evt);
            }
        });
        pEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1045, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Contenedor.setPreferredSize(new java.awt.Dimension(1200, 590));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1248, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseClicked

    private void pEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseEntered
        // TODO add your handling code here:;
        pEmpleado.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_pEmpleadoMouseEntered

    private void pEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseExited
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseExited

    private void pEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMousePressed
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_pEmpleadoMousePressed

    private void pEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseReleased
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseReleased

    private void pEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmpleadoActionPerformed
        // TODO add your handling code here:
//        frmEmpleado emp = new frmEmpleado();
//        emp.setSize(1200, 590);
//        emp.setLocation(0, 0);
//        Contenedor.removeAll();
//        Contenedor.add(emp, BorderLayout.CENTER);
//        Contenedor.revalidate();
//        Contenedor.repaint();

        //Adding last three entries from every categories in home
    }//GEN-LAST:event_pEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pEmpleado;
    // End of variables declaration//GEN-END:variables
}
