/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forularios;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Eterna
 */
public class frmProc extends javax.swing.JPanel {

    /**
     * Creates new form frmProc
     */
    public frmProc() {
        initComponents();
       
//        bnt_siguiente.setEnabled(false);
//        bnt_siguiente.setVisible(false);
//        cEmpleado.setEnabled(false);
//        sConstancia1.setEnabled(false);
//        sConstancia.setEnabled(false);
//        btnIss.setEnabled(false);
    }
    public int contador;
    public void fGravado(){
    
        frmsGravado fISS = new frmsGravado();
        fISS.setSize(945, 510);
        fISS.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(fISS, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        btnIss.setBackground(new Color(0, 137, 123));
        bEmpleado1.setEnabled(true);
        bEmpleado1.setBackground(Color.GREEN);
        bEmpleado1.setText("Siguiente");

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        pEmpleado = new javax.swing.JButton();
        bEmpleado1 = new javax.swing.JButton();
        cEmpleado = new javax.swing.JButton();
        sConstancia = new javax.swing.JButton();
        sConstancia1 = new javax.swing.JButton();
        bnt_siguiente = new javax.swing.JButton();
        btnIss = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 150, 136));
        setPreferredSize(new java.awt.Dimension(1360, 720));

        Contenedor.setPreferredSize(new java.awt.Dimension(1010, 570));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        pEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        pEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        pEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        pEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cacl.png"))); // NOI18N
        pEmpleado.setToolTipText("Check what's new!");
        pEmpleado.setBorderPainted(false);
        pEmpleado.setContentAreaFilled(false);
        pEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pEmpleado.setOpaque(true);
        pEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseReleased(evt);
            }
        });
        pEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmpleadoActionPerformed(evt);
            }
        });

        bEmpleado1.setBackground(new java.awt.Color(0, 150, 136));
        bEmpleado1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        bEmpleado1.setText("Aguinaldo");
        bEmpleado1.setToolTipText("Genere aguinaldo");
        bEmpleado1.setBorderPainted(false);
        bEmpleado1.setContentAreaFilled(false);
        bEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bEmpleado1.setOpaque(true);
        bEmpleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEmpleado1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEmpleado1MouseExited(evt);
            }
        });
        bEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpleado1ActionPerformed(evt);
            }
        });

        cEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        cEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        cEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        cEmpleado.setText("Vacaciones");
        cEmpleado.setToolTipText("Genere calculo de vacaciones");
        cEmpleado.setBorderPainted(false);
        cEmpleado.setContentAreaFilled(false);
        cEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cEmpleado.setOpaque(true);
        cEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseReleased(evt);
            }
        });
        cEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmpleadoActionPerformed(evt);
            }
        });

        sConstancia.setBackground(new java.awt.Color(0, 150, 136));
        sConstancia.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        sConstancia.setForeground(new java.awt.Color(255, 255, 255));
        sConstancia.setText("ISR");
        sConstancia.setToolTipText("Genere calculo de renta");
        sConstancia.setBorderPainted(false);
        sConstancia.setContentAreaFilled(false);
        sConstancia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sConstancia.setOpaque(true);
        sConstancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sConstanciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sConstanciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sConstanciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sConstanciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sConstanciaMouseReleased(evt);
            }
        });
        sConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sConstanciaActionPerformed(evt);
            }
        });

        sConstancia1.setBackground(new java.awt.Color(0, 150, 136));
        sConstancia1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        sConstancia1.setForeground(new java.awt.Color(255, 255, 255));
        sConstancia1.setText("Horas extras");
        sConstancia1.setToolTipText("Genere calculo vacaciones");
        sConstancia1.setBorderPainted(false);
        sConstancia1.setContentAreaFilled(false);
        sConstancia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sConstancia1.setOpaque(true);
        sConstancia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sConstancia1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sConstancia1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sConstancia1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sConstancia1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sConstancia1MouseReleased(evt);
            }
        });
        sConstancia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sConstancia1ActionPerformed(evt);
            }
        });

        bnt_siguiente.setBackground(new java.awt.Color(153, 255, 153));
        bnt_siguiente.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bnt_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        bnt_siguiente.setText("Siguiente");
        bnt_siguiente.setToolTipText("Genere calculo de renta");
        bnt_siguiente.setBorderPainted(false);
        bnt_siguiente.setContentAreaFilled(false);
        bnt_siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnt_siguiente.setOpaque(true);
        bnt_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_siguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnt_siguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnt_siguienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bnt_siguienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bnt_siguienteMouseReleased(evt);
            }
        });
        bnt_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_siguienteActionPerformed(evt);
            }
        });

        btnIss.setBackground(new java.awt.Color(0, 150, 136));
        btnIss.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        btnIss.setForeground(new java.awt.Color(255, 255, 255));
        btnIss.setText("Salario Gravado");
        btnIss.setToolTipText("Genere renta imponible");
        btnIss.setBorderPainted(false);
        btnIss.setContentAreaFilled(false);
        btnIss.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIss.setOpaque(true);
        btnIss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIssMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIssMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIssMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIssMouseReleased(evt);
            }
        });
        btnIss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sConstancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnIss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(sConstancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bnt_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(pEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEmpleado)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sConstancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIss, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sConstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(bnt_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseClicked

    private void pEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseEntered
        // TODO add your handling code here:;
    }//GEN-LAST:event_pEmpleadoMouseEntered

    private void pEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseExited

    private void pEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMousePressed

    private void pEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseReleased

    private void pEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmpleadoActionPerformed
        // TODO add your handling code here:
//        frmPerfilEmp emp = new frmPerfilEmp();
//        emp.setSize(1200, 590);
//        emp.setLocation(0, 0);
//        Contenedor.removeAll();
//        Contenedor.add(emp, BorderLayout.CENTER);
//        Contenedor.revalidate();
//        Contenedor.repaint();

        //Adding last three entries from every categories in home
    }//GEN-LAST:event_pEmpleadoActionPerformed

    private void sConstanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMouseClicked

    private void sConstanciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMouseEntered

    private void sConstanciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMouseExited

    private void sConstanciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMousePressed

    private void sConstanciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMouseReleased

    private void sConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sConstanciaActionPerformed
        // TODO add your handling code here:
        bEmpleado1.setBackground(new Color(0, 150, 136));
        btnIss.setBackground(new Color(0, 150, 136));
        frmCalculoRenta cacl = new frmCalculoRenta();
        cacl.setSize(1200, 590);
        cacl.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(cacl, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        sConstancia.setText("Calculo de renta");
        sConstancia.setBackground(new Color(0, 137, 123));
        sConstancia1.setBackground(new Color(0, 150, 136));
        cEmpleado.setBackground(new Color(0, 150, 136));
        sConstancia1.setEnabled(true);
        bnt_siguiente.setEnabled(true);
        bnt_siguiente.setVisible(true);
        btnIss.setEnabled(true);
        cEmpleado.setEnabled(true);
        bEmpleado1.setEnabled(true);
        sConstancia1.setEnabled(true);
        sConstancia.setEnabled(true);
//        contador=2;
    }//GEN-LAST:event_sConstanciaActionPerformed

    private void cEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMouseClicked

    private void cEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMouseEntered

    private void cEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMouseExited

    private void cEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMousePressed

    private void cEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMouseReleased

    private void cEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmpleadoActionPerformed
    // TODO add your handling code here:
        btnIss.setBackground(new Color(0, 150, 136));
        sConstancia1.setBackground(new Color(0, 150, 136));
        sConstancia.setBackground(new Color(0, 150, 136));
        frmVacaciones fVac = new frmVacaciones();
        fVac.setSize(945, 510);
        fVac.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(fVac, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        cEmpleado.setText("Calculo de Vacaciones");
        cEmpleado.setBackground(new Color(0, 137, 123));
        bEmpleado1.setBackground(new Color(0, 150, 136));
//        if(contador<1){
//         sConstancia1.setText("Siguiente");
//            sConstancia1.setBackground(Color.GREEN);
//            sConstancia1.setEnabled(true);
//            bEmpleado1.setEnabled(false);
//        }


    }//GEN-LAST:event_cEmpleadoActionPerformed

    private void btnIssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssMouseClicked

    private void btnIssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssMouseEntered
        // TODO add your handling code here:
//        btnIss.setBackground(new Color(0, 137, 123));

    }//GEN-LAST:event_btnIssMouseEntered

    private void btnIssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssMouseExited
        // TODO add your handling code here:
//       btnIss.setBackground(new Color(0, 150, 136));

    }//GEN-LAST:event_btnIssMouseExited

    private void btnIssMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssMousePressed

    private void btnIssMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssMouseReleased

    private void btnIssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssActionPerformed
        // TODO add your handling code here:

        bEmpleado1.setBackground(new Color(0, 150, 136));
        cEmpleado.setBackground(new Color(0, 150, 136));
        sConstancia1.setBackground(new Color(0, 150, 136));
        sConstancia.setBackground(new Color(0, 150, 136));
        btnIss.setBackground(new Color(0, 137, 123));

        frmsGravado fISS = new frmsGravado();
        fISS.setSize(945, 510);
        fISS.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(fISS, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btnIssActionPerformed

    private void sConstancia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstancia1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_sConstancia1MouseClicked

    private void sConstancia1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstancia1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_sConstancia1MouseEntered

    private void sConstancia1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstancia1MouseExited
        // TODO add your handling code here:
        
//


    }//GEN-LAST:event_sConstancia1MouseExited

    private void sConstancia1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstancia1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstancia1MousePressed

    private void sConstancia1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstancia1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstancia1MouseReleased

    private void sConstancia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sConstancia1ActionPerformed
        // TODO add your handling code here:
        bEmpleado1.setBackground(new Color(0, 150, 136));
        btnIss.setBackground(new Color(0, 150, 136));
        sConstancia.setBackground(new Color(0, 150, 136));
        frmHorasExtras horas = new frmHorasExtras();
        horas.setSize(1200, 590);
        horas.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(horas, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        cEmpleado.setBackground(new Color(0, 150, 136));
        sConstancia1.setText("Calculo horas extras");
        sConstancia1.setBackground(new Color(0, 137, 123));
//        if(contador<1){
//          sConstancia.setText("Siguiente");
//          sConstancia.setBackground(Color.GREEN);
//          sConstancia.setEnabled(true);
//          cEmpleado.setEnabled(false);
//        };

        
        
        
    }//GEN-LAST:event_sConstancia1ActionPerformed

    private void bEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpleado1ActionPerformed
        // TODO add your handling code here:
        sConstancia.setBackground(new Color(0, 150, 136));
        sConstancia1.setBackground(new Color(0, 150, 136));
        cEmpleado.setBackground(new Color(0, 150, 136));


      frmAguinaldo fAgui = new frmAguinaldo();
        fAgui.setSize(1200, 590);
        fAgui.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(fAgui, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        btnIss.setBackground(new Color(0, 150, 136));
        bEmpleado1.setBackground(new Color(0, 137, 123));
        bEmpleado1.setText("Calculo de aguinaldo");
//        if(contador<1){
//            cEmpleado.setEnabled(true);
//            cEmpleado.setText("Siguiente");
//            cEmpleado.setBackground(Color.green); 
//        }

        
        
        
    }//GEN-LAST:event_bEmpleado1ActionPerformed

    private void bEmpleado1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEmpleado1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_bEmpleado1MouseExited

    private void bEmpleado1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEmpleado1MouseEntered
        // TODO add your handling code here:

                
    }//GEN-LAST:event_bEmpleado1MouseEntered

    private void bnt_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_siguienteActionPerformed
        // TODO add your handling code here:
//        prueba bp = new prueba();
//        bp.setVisible(true);
//        bp.setSize(1360, 720);
//        bp.setLocation(0, 0);


        cEmpleado.setEnabled(false);
        sConstancia1.setEnabled(false);
        sConstancia.setEnabled(false);
        btnIss.setEnabled(false);
        sConstancia1.setVisible(false);
        sConstancia.setVisible(false);
        btnIss.setVisible(false);
        Contenedor.setVisible(false);
        
        cEmpleado.setVisible(false);
        pEmpleado.setVisible(false);
        bEmpleado1.setVisible(false);
        bnt_siguiente.setVisible(false);

    }//GEN-LAST:event_bnt_siguienteActionPerformed

    private void bnt_siguienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_siguienteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguienteMouseReleased

    private void bnt_siguienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_siguienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguienteMousePressed

    private void bnt_siguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_siguienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguienteMouseExited

    private void bnt_siguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_siguienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguienteMouseEntered

    private void bnt_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_siguienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_siguienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Contenedor;
    public javax.swing.JButton bEmpleado1;
    private javax.swing.JButton bnt_siguiente;
    private javax.swing.JButton btnIss;
    private javax.swing.JButton cEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton pEmpleado;
    private javax.swing.JButton sConstancia;
    private javax.swing.JButton sConstancia1;
    // End of variables declaration//GEN-END:variables
}
