/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forularios;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class frmVacaciones extends javax.swing.JPanel {

    /**
     * Creates new form frmVacaciones
     */
    DecimalFormat df = new DecimalFormat();
    frmPerfilEmp emp = new frmPerfilEmp();
    double salMes, afpMes, isssMes, salGravado, salLiquiido, temp;
    
    public frmVacaciones() {
        initComponents();
        calculoMes();
        calculoAFPMes();
        calculoISSS();
        setGravado();
        //calcularRentar();
        
    }
    
    public void calculoMes() {
    
        
        salMes = (emp.sueldo1/2) * 1.3 + (emp.sueldo1/2);
        this.lblIngresoMes.setText("" + salMes);
    }

    public void calculoAFPMes() {
    
        
        afpMes = salMes * 0.0725;
        this.lblAFPdelMes.setText(""+afpMes);
    }
    
    public void calculoISSS() {
    
        
        if(salMes > 1000) {
            isssMes = 30;
            this.lblISSSMes.setText(""+isssMes);
        }
        else
        {
            isssMes = salMes * 0.03;
            this.lblISSSMes.setText(""+isssMes);
        }
    }
    
    public void setGravado() {
    
        salGravado = salMes - afpMes - isssMes;

        this.lblRemuMes.setText("$"+df.format(salGravado));
    }
    
    //PORQUE SE CALCULA LA RENTA DE NUEVO?
    
//    public void calcularRentar() {
//    
//         
//         
//        if(salGravado < 472 && salGravado> 0.01) {
//    
//             this.jLabel16.setText("Tramo 1. Sin retencion");
//
//        }
//        else if (salGravado >= 472.01 && salGravado <= 895.24) 
//        {
//            this.jLabel16.setText("Tramo 2. Retencion del 10%");
//            temp = salGravado;
//            temp = temp-472;
//            temp = temp * 0.1;
//            temp = temp + 17.67;
//            temp = salGravado - temp;
//            double temp2 = temp;
//            this.lblLiquido.setText(""+df.format(temp2)); 
//            
//           
//             
//
//        }
//        else if (salGravado >= 895.25 && salGravado <= 2038.10) 
//        {
//              this.jLabel16.setText("Tramo 3. Retencion del 20%");
//             temp = salGravado;
//             temp = temp-895.24;
//             temp = temp * 0.2;
//             temp = temp + 60;
//             temp = salGravado - temp;
//             
//              double temp2 = temp;
//              
//            this.lblLiquido.setText(""+df.format(temp2)); 
//        }
//        else if (salGravado > 2038.10){
//             this.jLabel16.setText("Tramo 4. Retencion del 30%");
//            temp = salGravado;
//            temp = temp-2038.10;
//            temp = temp * 0.3;
//            temp = temp + 288.57;
//            temp = salGravado - temp;
//            
//            double temp2 = temp;
//            this.lblLiquido.setText(""+df.format(temp2)); 
//            
//        }else{
//            JOptionPane.showMessageDialog(null,"A ocurrido un error");  
//        }             
//    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingreso_ = new javax.swing.JLabel();
        des_afp = new javax.swing.JLabel();
        des_iss = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIngresoMes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblAFPdelMes = new javax.swing.JLabel();
        lblISSSMes = new javax.swing.JLabel();
        lblRemuMes = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblLiquido = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingreso_.setText("$");
        add(ingreso_, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 50, -1));

        des_afp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        des_afp.setText("$");
        add(des_afp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 60, -1));

        des_iss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        des_iss.setText("$");
        add(des_iss, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 60, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ingresos del mes");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, -1));

        lblIngresoMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIngresoMes.setText(".");
        add(lblIngresoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("AFP Del mes");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ISSS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Descuentos");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Remuneracion gravada del mes");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, -1));

        lblAFPdelMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAFPdelMes.setText(".");
        add(lblAFPdelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 100, -1));

        lblISSSMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblISSSMes.setText(".");
        add(lblISSSMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 100, -1));

        lblRemuMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRemuMes.setText(".");
        add(lblRemuMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 165, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Remuneracion liquida");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("$");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        lblLiquido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLiquido.setText(".");
        add(lblLiquido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 350, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Ingresos");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Calculo de Vacaciones");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 420, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fvacaciones.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1190, 520));

        jLabel14.setText("Descuentos");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel des_afp;
    private javax.swing.JLabel des_iss;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel ingreso_;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAFPdelMes;
    private javax.swing.JLabel lblISSSMes;
    private javax.swing.JLabel lblIngresoMes;
    private javax.swing.JLabel lblLiquido;
    private javax.swing.JLabel lblRemuMes;
    // End of variables declaration//GEN-END:variables
}
