/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forularios;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Eterna
 */
public class mainEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form mainEmpleado
     */
    public mainEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Contenedor = new javax.swing.JPanel();
        btnproceso2 = new javax.swing.JButton();
        pEmpleado = new javax.swing.JButton();
        pBoleta = new javax.swing.JButton();
        cEmpleado = new javax.swing.JButton();
        sConstancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg_panel.setBackground(new java.awt.Color(0, 150, 136));
        bg_panel.setPreferredSize(new java.awt.Dimension(1360, 720));

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        Contenedor.setPreferredSize(new java.awt.Dimension(1360, 720));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        btnproceso2.setBackground(new java.awt.Color(0, 150, 136));
        btnproceso2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        btnproceso2.setForeground(new java.awt.Color(255, 255, 255));
        btnproceso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnproceso2.setToolTipText("Regrece a menu de selección");
        btnproceso2.setBorderPainted(false);
        btnproceso2.setContentAreaFilled(false);
        btnproceso2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnproceso2.setOpaque(true);
        btnproceso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproceso2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnproceso2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnproceso2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnproceso2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnproceso2MouseReleased(evt);
            }
        });
        btnproceso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproceso2ActionPerformed(evt);
            }
        });

        pEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        pEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        pEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        pEmpleado.setText("Perfil de empleado");
        pEmpleado.setToolTipText("Ingresa o seleccione empleado");
        pEmpleado.setBorderPainted(false);
        pEmpleado.setContentAreaFilled(false);
        pEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pEmpleado.setOpaque(true);
        pEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseReleased(evt);
            }
        });
        pEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmpleadoActionPerformed(evt);
            }
        });

        pBoleta.setBackground(new java.awt.Color(0, 150, 136));
        pBoleta.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        pBoleta.setForeground(new java.awt.Color(255, 255, 255));
        pBoleta.setText("Boleta de pago");
        pBoleta.setToolTipText("Genere Boleta de pago");
        pBoleta.setBorderPainted(false);
        pBoleta.setContentAreaFilled(false);
        pBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pBoleta.setOpaque(true);
        pBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pBoletaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pBoletaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pBoletaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pBoletaMouseReleased(evt);
            }
        });
        pBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBoletaActionPerformed(evt);
            }
        });

        cEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        cEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        cEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        cEmpleado.setText("Constancia para la declaración de la renta");
        cEmpleado.setToolTipText("Genera constancia de declaraciòn de renta");
        cEmpleado.setBorder(null);
        cEmpleado.setBorderPainted(false);
        cEmpleado.setContentAreaFilled(false);
        cEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cEmpleado.setOpaque(true);
        cEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cEmpleadoMouseReleased(evt);
            }
        });
        cEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmpleadoActionPerformed(evt);
            }
        });

        sConstancia.setBackground(new java.awt.Color(0, 150, 136));
        sConstancia.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        sConstancia.setForeground(new java.awt.Color(255, 255, 255));
        sConstancia.setText("Constancia de sueldo");
        sConstancia.setToolTipText("Generar constancia de sueldo");
        sConstancia.setBorderPainted(false);
        sConstancia.setContentAreaFilled(false);
        sConstancia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sConstancia.setOpaque(true);
        sConstancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sConstanciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sConstanciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sConstanciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sConstanciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sConstanciaMouseReleased(evt);
            }
        });
        sConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sConstanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnproceso2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pBoleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sConstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnproceso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sConstancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseClicked

    private void pEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseEntered
        // TODO add your handling code here:;
        pEmpleado.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_pEmpleadoMouseEntered

    private void pEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseExited
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseExited

    private void pEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMousePressed
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_pEmpleadoMousePressed

    private void pEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseReleased
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseReleased

    private void pEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmpleadoActionPerformed
        // TODO add your handling code here:
        frmPerfilEmp emp = new frmPerfilEmp();
        emp.setSize(1360, 720);
        emp.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(emp, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        //Adding last three entries from every categories in home
    }//GEN-LAST:event_pEmpleadoActionPerformed

    private void btnproceso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceso2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproceso2MouseClicked

    private void btnproceso2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceso2MouseEntered
        // TODO add your handling code here:
        btnproceso2.setBackground(new Color(0, 137, 123));

    }//GEN-LAST:event_btnproceso2MouseEntered

    private void btnproceso2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceso2MouseExited
        // TODO add your handling code here:
        btnproceso2.setBackground(new Color(0, 150, 136));

    }//GEN-LAST:event_btnproceso2MouseExited

    private void btnproceso2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceso2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproceso2MousePressed

    private void btnproceso2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproceso2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproceso2MouseReleased

    private void btnproceso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproceso2ActionPerformed
        // TODO add your handling code here:
        MainForm main = new MainForm();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnproceso2ActionPerformed

    private void cEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoActionPerformed

    private void cEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseReleased
        // TODO add your handling code here:
        cEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_cEmpleadoMouseReleased

    private void cEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMousePressed
        // TODO add your handling code here:
        cEmpleado.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_cEmpleadoMousePressed

    private void cEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseExited
        // TODO add your handling code here:
        cEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_cEmpleadoMouseExited

    private void cEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseEntered
        // TODO add your handling code here:
        cEmpleado.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_cEmpleadoMouseEntered

    private void cEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpleadoMouseClicked

    private void sConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sConstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaActionPerformed

    private void sConstanciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseReleased
        // TODO add your handling code here:
        sConstancia.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_sConstanciaMouseReleased

    private void sConstanciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMousePressed
        // TODO add your handling code here:
        sConstancia.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_sConstanciaMousePressed

    private void sConstanciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseExited
        // TODO add your handling code here:
        sConstancia.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_sConstanciaMouseExited

    private void sConstanciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseEntered
        // TODO add your handling code here:
        sConstancia.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_sConstanciaMouseEntered

    private void sConstanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sConstanciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sConstanciaMouseClicked

    private void pBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBoletaActionPerformed
        // TODO add your handling code here:
        frmBoltaP emp = new frmBoltaP();
        emp.setSize(1360, 720);
        emp.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(emp, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_pBoletaActionPerformed

    private void pBoletaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBoletaMouseEntered
        // TODO add your handling code here:
         pBoleta.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_pBoletaMouseEntered

    private void pBoletaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBoletaMouseExited
        // TODO add your handling code here:
          pBoleta.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pBoletaMouseExited

    private void pBoletaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBoletaMousePressed
        // TODO add your handling code here:
         pBoleta.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_pBoletaMousePressed

    private void pBoletaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBoletaMouseReleased
        // TODO add your handling code here:
        pBoleta.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pBoletaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JButton btnproceso2;
    private javax.swing.JButton cEmpleado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pBoleta;
    private javax.swing.JButton pEmpleado;
    private javax.swing.JButton sConstancia;
    // End of variables declaration//GEN-END:variables
}
