/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forularios;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Eterna
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);		

 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pEmpleado = new javax.swing.JButton();
        Empresa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 200));
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg_panel.setBackground(new java.awt.Color(0, 121, 107));
        bg_panel.setPreferredSize(new java.awt.Dimension(400, 200));

        jPanel2.setBackground(new java.awt.Color(0, 121, 107));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión Documental ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 200));

        pEmpleado.setBackground(new java.awt.Color(0, 150, 136));
        pEmpleado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        pEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        pEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        pEmpleado.setText("Empleado");
        pEmpleado.setToolTipText("Check what's new!");
        pEmpleado.setBorderPainted(false);
        pEmpleado.setContentAreaFilled(false);
        pEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pEmpleado.setOpaque(true);
        pEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEmpleadoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEmpleadoMouseReleased(evt);
            }
        });
        pEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmpleadoActionPerformed(evt);
            }
        });

        Empresa.setBackground(new java.awt.Color(0, 150, 136));
        Empresa.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Empresa.setForeground(new java.awt.Color(255, 255, 255));
        Empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empresa.png"))); // NOI18N
        Empresa.setText("Empresa");
        Empresa.setToolTipText("View your cart.");
        Empresa.setBorderPainted(false);
        Empresa.setContentAreaFilled(false);
        Empresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Empresa.setMaximumSize(new java.awt.Dimension(67, 49));
        Empresa.setOpaque(true);
        Empresa.setPreferredSize(new java.awt.Dimension(67, 49));
        Empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpresaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmpresaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EmpresaMouseReleased(evt);
            }
        });
        Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
            .addComponent(pEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione panel al que desea acceder:");

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_panelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpleadoMouseClicked

    private void pEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseEntered
        // TODO add your handling code here:;
        pEmpleado.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_pEmpleadoMouseEntered

    private void pEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseExited
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseExited

    private void pEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMousePressed
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_pEmpleadoMousePressed

    private void pEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEmpleadoMouseReleased
        // TODO add your handling code here:
        pEmpleado.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_pEmpleadoMouseReleased

    private void pEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmpleadoActionPerformed
        // TODO add your handling code here:    
       
        mainEmpleado emp = new mainEmpleado();
//        emp.setSize(1200, 590);
//        emp.setLocation(0, 0);
        emp.setVisible(true);
        this.setVisible(false);

        //Adding last three entries from every categories in home

    }//GEN-LAST:event_pEmpleadoActionPerformed

    private void EmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpresaMouseClicked

    private void EmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseEntered
        // TODO add your handling code here:
        Empresa.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_EmpresaMouseEntered

    private void EmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseExited
        // TODO add your handling code here:
        Empresa.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_EmpresaMouseExited

    private void EmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMousePressed
        // TODO add your handling code here:
        Empresa.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_EmpresaMousePressed

    private void EmpresaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpresaMouseReleased
        // TODO add your handling code here:
        Empresa.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_EmpresaMouseReleased

    private void EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaActionPerformed
        frmEmpresa emp = new frmEmpresa();
        emp.setSize(1200, 590);
        emp.setLocation(0, 0);
        

    }//GEN-LAST:event_EmpresaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Empresa;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pEmpleado;
    // End of variables declaration//GEN-END:variables
}
